import { GamesRes } from './games.models';

export const derehamFixturesData: GamesRes = {
  'fixtures-results': {
    team: {
      name: 'Dereham Town',
      id: 708,
    },
    matches: [
      {
        date: '2022-08-05',
        venue: 'Trafford Park',
        round: {
          name: 'Extra Preliminary Round',
          id: 1,
        },
        competition: {
          name: 'Emirates FA Cup',
          id: 21,
        },
        id: 421896,
        time: '19:45',
        'home-team': {
          score: 1,
          'half-time-score': 1,
          name: 'Wroxham',
          id: 816,
        },
        referee: 'Andrew Tregoning',
        'away-team': {
          score: 2,
          'half-time-score': 1,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 520,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-08-13',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419589,
        time: '15:00',
        'home-team': {
          score: 1,
          'half-time-score': 1,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 1,
          'half-time-score': 1,
          name: 'Hinckley LRFC',
          id: 2588,
        },
        attendance: 178,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-08-16',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419603,
        time: '19:45',
        'home-team': {
          score: 2,
          'half-time-score': 2,
          name: 'Shepshed Dynamo',
          id: 323,
        },
        'away-team': {
          score: 2,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 198,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-08-20',
        venue: 'Aldiss Park',
        round: {
          name: 'Preliminary Round',
          id: 3,
        },
        competition: {
          name: 'Emirates FA Cup',
          id: 21,
        },
        id: 422728,
        time: '15:00',
        'home-team': {
          score: 2,
          'half-time-score': 2,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'J Coupar',
        'away-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Felixstowe & Walton United',
          id: 716,
        },
        attendance: 229,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-08-23',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419608,
        time: '19:45',
        'home-team': {
          score: 1,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'A George',
        'away-team': {
          score: 3,
          'half-time-score': 1,
          name: 'Stamford',
          id: 178,
        },
        attendance: 154,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-08-27',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419621,
        time: '15:00',
        'home-team': {
          score: 2,
          'half-time-score': 0,
          name: 'Daventry Town',
          id: 707,
        },
        referee: 'Daniel Stokes',
        'away-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 94,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-08-29',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419629,
        time: '15:00',
        'home-team': {
          score: 1,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'T Harvey',
        'away-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Cambridge City',
          id: 140,
        },
        attendance: 272,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-09-03',
        venue: 'Aldiss Park',
        round: {
          name: 'First Qualifying Round',
          id: 5,
        },
        competition: {
          name: 'Emirates FA Cup',
          id: 21,
        },
        id: 423397,
        time: '15:00',
        'home-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'C Darling',
        'away-team': {
          score: 1,
          'half-time-score': 0,
          name: 'Biggleswade Town',
          id: 945,
        },
        attendance: 217,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-09-06',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419640,
        time: '19:45',
        'home-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'B Green',
        'away-team': {
          score: 2,
          'half-time-score': 0,
          name: 'Spalding United',
          id: 324,
        },
        attendance: 186,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-09-13',
        venue: 'Hillgrounds Leisure',
        round: {
          name: 'First Qualifying Round',
          id: 5,
        },
        competition: {
          name: 'Isuzu FA Trophy',
          id: 27,
        },
        id: 425153,
        time: '19:45',
        'home-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Kempston Rovers',
          id: 1048,
        },
        referee: 'S Lee',
        'away-team': {
          score: 1,
          'half-time-score': 1,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 58,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-09-17',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419661,
        time: '15:00',
        'home-team': {
          score: 2,
          'half-time-score': 1,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'Ian Ruddock',
        'away-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Gresley Rovers',
          id: 314,
        },
        attendance: 172,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-09-24',
        venue: 'Aldiss Park',
        round: {
          name: 'Second Qualifying Round',
          id: 7,
        },
        competition: {
          name: 'Isuzu FA Trophy',
          id: 27,
        },
        id: 425278,
        time: '15:00',
        'home-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'B Mingay',
        'away-team': {
          score: 1,
          'half-time-score': 0,
          name: 'Spalding United',
          id: 324,
        },
        attendance: 162,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-10-01',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419668,
        time: '15:00',
        'home-team': {
          score: 3,
          'half-time-score': 2,
          name: 'Boldmere St Michaels',
          id: 830,
        },
        referee: 'Martyn Mitchell',
        'away-team': {
          score: 1,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 105,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-10-08',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 425931,
        time: '15:00',
        'home-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'T Harvey',
        'away-team': {
          score: 2,
          'half-time-score': 1,
          name: 'Bedworth United',
          id: 204,
        },
        attendance: 181,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-10-15',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419690,
        time: '15:00',
        'home-team': {
          score: 3,
          'half-time-score': 1,
          name: 'Coleshill Town',
          id: 700,
        },
        referee: 'Simon kavanagh',
        'away-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 105,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-10-18',
        venue: 'The Premier Plus Stadium',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 425525,
        time: '19:45',
        'home-team': {
          score: 1,
          'half-time-score': 1,
          name: 'St Neots Town',
          id: 895,
        },
        'away-team': {
          score: 3,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 132,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-10-22',
        venue: 'Steel Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419700,
        time: '15:00',
        'home-team': {
          score: 3,
          'half-time-score': 2,
          name: 'Corby Town',
          id: 211,
        },
        referee: 'Joe Woolmer',
        'away-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 432,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-10-29',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419709,
        time: '15:00',
        'home-team': {
          score: 1,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'A Wilson',
        'away-team': {
          score: 1,
          'half-time-score': 0,
          name: 'Loughborough Dynamo',
          id: 749,
        },
        attendance: 208,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-11-01',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 425960,
        time: '19:45',
        'home-team': {
          score: 3,
          'half-time-score': 2,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'A George',
        'away-team': {
          score: 2,
          'half-time-score': 1,
          name: 'Sutton Coldfield Town',
          id: 220,
        },
        attendance: 146,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-11-05',
        venue: 'The Grove',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419722,
        time: '15:00',
        'home-team': {
          score: 4,
          'half-time-score': 3,
          name: 'Halesowen Town',
          id: 169,
        },
        referee: 'Brandon Scaife',
        'away-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 1087,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-11-12',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419729,
        time: '15:00',
        'home-team': {
          score: 2,
          'half-time-score': 2,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'B Green',
        'away-team': {
          score: 3,
          'half-time-score': 1,
          name: 'Chasetown',
          id: 384,
        },
        attendance: 221,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-11-19',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419742,
        time: '15:00',
        'home-team': {
          score: 3,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        referee: 'P Quick',
        'away-team': {
          score: 2,
          'half-time-score': 0,
          name: 'Harborough Town',
          id: 1415,
        },
        attendance: 212,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-11-26',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419754,
        time: '15:00',
        'home-team': {
          score: 5,
          'half-time-score': 4,
          name: 'Sporting Khalsa',
          id: 1554,
        },
        referee: 'M Billingham ',
        'away-team': {
          score: 0,
          'half-time-score': 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 183,
        status: {
          short: 'FT',
          full: 'Full Time',
        },
      },
      {
        date: '2022-12-17',
        venue: 'Leicester Road Stadium',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419783,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Hinckley LRFC',
          id: 2588,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2022-12-26',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419789,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'Yaxley',
          id: 474,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-01-02',
        venue: 'The Glassworld Stadium (Histon FC)',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419798,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Cambridge City',
          id: 140,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-01-07',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419809,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'Shepshed Dynamo',
          id: 323,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-01-14',
        venue: 'Zeeco Stadium',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419825,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Stamford',
          id: 178,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-01-21',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419831,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'St Neots Town',
          id: 895,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-01-28',
        venue: 'The Oval',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419837,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Bedworth United',
          id: 204,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-02-04',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419851,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'Boldmere St Michaels',
          id: 830,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-02-07',
        venue: 'Sir Halley Stewart Playing Field',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419862,
        time: '19:45',
        'home-team': {
          score: 0,
          name: 'Spalding United',
          id: 324,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '7.45pm',
          full: 'Kick off 7.45pm',
        },
      },
      {
        date: '2023-02-11',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 428344,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Gresley Rovers',
          id: 314,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-02-18',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419870,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'Coleshill Town',
          id: 700,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-02-25',
        venue: 'Central Ground',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419885,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Sutton Coldfield Town',
          id: 220,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-03-04',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419889,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'Corby Town',
          id: 211,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-03-18',
        venue: 'The Newton Fallowell Stadium',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419904,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Loughborough Dynamo',
          id: 749,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-03-25',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419909,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'Halesowen Town',
          id: 169,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-04-01',
        venue: 'The Scholars Ground',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419919,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Chasetown',
          id: 384,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-04-08',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419929,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'Daventry Town',
          id: 707,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-04-10',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419946,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Yaxley',
          id: 474,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-04-15',
        venue: 'Aldiss Park',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419952,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        'away-team': {
          score: 0,
          name: 'Sporting Khalsa',
          id: 1554,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
      {
        date: '2023-04-22',
        competition: {
          name: 'Northern Premier League - Midlands Division',
          id: 114,
        },
        id: 419961,
        time: '15:00',
        'home-team': {
          score: 0,
          name: 'Harborough Town',
          id: 1415,
        },
        'away-team': {
          score: 0,
          name: 'Dereham Town',
          id: 708,
        },
        attendance: 0,
        status: {
          short: '3pm',
          full: 'Kick off 3pm',
        },
      },
    ],
  },
};
