import { LeagueTableRes } from './leagueTable.models';

export const premierLeagueData: LeagueTableRes = {
  'league-table': {
    teams: [
      {
        'all-matches': {
          lost: 1,
          against: 11,
          'goal-difference': 22,
          won: 12,
          for: 33,
          drawn: 1,
          played: 14,
        },
        zone: 'Promotion',
        name: 'Arsenal',
        'home-matches': {
          lost: 0,
          against: 7,
          won: 6,
          for: 19,
          drawn: 0,
          played: 6,
        },
        'away-matches': {
          lost: 1,
          against: 4,
          won: 6,
          for: 14,
          drawn: 1,
          played: 8,
        },
        id: 1,
        position: 1,
        'total-points': 37,
      },
      {
        'all-matches': {
          lost: 2,
          against: 14,
          'goal-difference': 26,
          won: 10,
          for: 40,
          drawn: 2,
          played: 14,
        },
        zone: 'Promotion',
        name: 'Manchester City',
        'home-matches': {
          lost: 1,
          against: 9,
          won: 7,
          for: 30,
          drawn: 0,
          played: 8,
        },
        'away-matches': {
          lost: 1,
          against: 5,
          won: 3,
          for: 10,
          drawn: 2,
          played: 6,
        },
        id: 12,
        position: 2,
        'total-points': 32,
      },
      {
        'all-matches': {
          lost: 1,
          against: 11,
          'goal-difference': 18,
          won: 8,
          for: 29,
          drawn: 6,
          played: 15,
        },
        zone: 'Promotion',
        name: 'Newcastle United',
        'home-matches': {
          lost: 0,
          against: 5,
          won: 5,
          for: 17,
          drawn: 3,
          played: 8,
        },
        'away-matches': {
          lost: 1,
          against: 6,
          won: 3,
          for: 12,
          drawn: 3,
          played: 7,
        },
        id: 15,
        position: 3,
        'total-points': 30,
      },
      {
        'all-matches': {
          lost: 4,
          against: 21,
          'goal-difference': 10,
          won: 9,
          for: 31,
          drawn: 2,
          played: 15,
        },
        zone: 'Promotion',
        name: 'Tottenham Hotspur',
        'home-matches': {
          lost: 2,
          against: 11,
          won: 6,
          for: 21,
          drawn: 0,
          played: 8,
        },
        'away-matches': {
          lost: 2,
          against: 10,
          won: 3,
          for: 10,
          drawn: 2,
          played: 7,
        },
        id: 19,
        position: 4,
        'total-points': 29,
      },
      {
        'all-matches': {
          lost: 4,
          against: 20,
          'goal-difference': 0,
          won: 8,
          for: 20,
          drawn: 2,
          played: 14,
        },
        zone: 'Play-offs',
        name: 'Manchester United',
        'home-matches': {
          lost: 1,
          against: 4,
          won: 4,
          for: 9,
          drawn: 1,
          played: 6,
        },
        'away-matches': {
          lost: 3,
          against: 16,
          won: 4,
          for: 11,
          drawn: 1,
          played: 8,
        },
        id: 13,
        position: 5,
        'total-points': 26,
      },
      {
        'all-matches': {
          lost: 4,
          against: 17,
          'goal-difference': 11,
          won: 6,
          for: 28,
          drawn: 4,
          played: 14,
        },
        zone: 'Play-offs',
        name: 'Liverpool',
        'home-matches': {
          lost: 1,
          against: 8,
          won: 5,
          for: 21,
          drawn: 2,
          played: 8,
        },
        'away-matches': {
          lost: 3,
          against: 9,
          won: 1,
          for: 7,
          drawn: 2,
          played: 6,
        },
        id: 11,
        position: 6,
        'total-points': 22,
      },
      {
        'all-matches': {
          lost: 5,
          against: 19,
          'goal-difference': 4,
          won: 6,
          for: 23,
          drawn: 3,
          played: 14,
        },
        zone: 'Play-offs (down)',
        name: 'Brighton & Hove Albion',
        'home-matches': {
          lost: 2,
          against: 6,
          won: 3,
          for: 11,
          drawn: 2,
          played: 7,
        },
        'away-matches': {
          lost: 3,
          against: 13,
          won: 3,
          for: 12,
          drawn: 1,
          played: 7,
        },
        id: 21,
        position: 7,
        'total-points': 21,
      },
      {
        'all-matches': {
          lost: 5,
          against: 17,
          'goal-difference': 0,
          won: 6,
          for: 17,
          drawn: 3,
          played: 14,
        },
        zone: 'Play-offs (down)',
        name: 'Chelsea',
        'home-matches': {
          lost: 1,
          against: 6,
          won: 3,
          for: 10,
          drawn: 2,
          played: 6,
        },
        'away-matches': {
          lost: 4,
          against: 11,
          won: 3,
          for: 7,
          drawn: 1,
          played: 8,
        },
        id: 7,
        position: 8,
        'total-points': 21,
      },
      {
        'all-matches': {
          lost: 6,
          against: 26,
          'goal-difference': -2,
          won: 5,
          for: 24,
          drawn: 4,
          played: 15,
        },
        zone: 'Play-offs (down)',
        name: 'Fulham',
        'home-matches': {
          lost: 2,
          against: 13,
          won: 3,
          for: 14,
          drawn: 3,
          played: 8,
        },
        'away-matches': {
          lost: 4,
          against: 13,
          won: 2,
          for: 10,
          drawn: 1,
          played: 7,
        },
        id: 10,
        position: 9,
        'total-points': 19,
      },
      {
        'all-matches': {
          lost: 4,
          against: 25,
          'goal-difference': -2,
          won: 4,
          for: 23,
          drawn: 7,
          played: 15,
        },
        zone: 'Play-offs (down)',
        name: 'Brentford',
        'home-matches': {
          lost: 1,
          against: 7,
          won: 3,
          for: 13,
          drawn: 3,
          played: 7,
        },
        'away-matches': {
          lost: 3,
          against: 18,
          won: 1,
          for: 10,
          drawn: 4,
          played: 8,
        },
        id: 49,
        position: 10,
        'total-points': 19,
      },
      {
        'all-matches': {
          lost: 5,
          against: 18,
          'goal-difference': -3,
          won: 5,
          for: 15,
          drawn: 4,
          played: 14,
        },
        zone: 'Play-offs (down)',
        name: 'Crystal Palace',
        'home-matches': {
          lost: 2,
          against: 8,
          won: 4,
          for: 10,
          drawn: 1,
          played: 7,
        },
        'away-matches': {
          lost: 3,
          against: 10,
          won: 1,
          for: 5,
          drawn: 3,
          played: 7,
        },
        id: 8,
        position: 11,
        'total-points': 19,
      },
      {
        'all-matches': {
          lost: 7,
          against: 22,
          'goal-difference': -6,
          won: 5,
          for: 16,
          drawn: 3,
          played: 15,
        },
        zone: 'Play-offs (down)',
        name: 'Aston Villa',
        'home-matches': {
          lost: 2,
          against: 6,
          won: 4,
          for: 11,
          drawn: 1,
          played: 7,
        },
        'away-matches': {
          lost: 5,
          against: 16,
          won: 1,
          for: 5,
          drawn: 2,
          played: 8,
        },
        id: 2,
        position: 12,
        'total-points': 18,
      },
      {
        'all-matches': {
          lost: 8,
          against: 25,
          'goal-difference': 0,
          won: 5,
          for: 25,
          drawn: 2,
          played: 15,
        },
        zone: 'Play-offs (down)',
        name: 'Leicester City',
        'home-matches': {
          lost: 3,
          against: 6,
          won: 2,
          for: 9,
          drawn: 2,
          played: 7,
        },
        'away-matches': {
          lost: 5,
          against: 19,
          won: 3,
          for: 16,
          drawn: 0,
          played: 8,
        },
        id: 30,
        position: 13,
        'total-points': 17,
      },
      {
        'all-matches': {
          lost: 7,
          against: 32,
          'goal-difference': -14,
          won: 4,
          for: 18,
          drawn: 4,
          played: 15,
        },
        zone: 'Play-offs (down)',
        name: 'AFC Bournemouth',
        'home-matches': {
          lost: 3,
          against: 8,
          won: 3,
          for: 9,
          drawn: 2,
          played: 8,
        },
        'away-matches': {
          lost: 4,
          against: 24,
          won: 1,
          for: 9,
          drawn: 2,
          played: 7,
        },
        id: 47,
        position: 14,
        'total-points': 16,
      },
      {
        'all-matches': {
          lost: 7,
          against: 26,
          'goal-difference': -4,
          won: 4,
          for: 22,
          drawn: 3,
          played: 14,
        },
        zone: 'Play-offs (down)',
        name: 'Leeds United',
        'home-matches': {
          lost: 2,
          against: 9,
          won: 3,
          for: 12,
          drawn: 2,
          played: 7,
        },
        'away-matches': {
          lost: 5,
          against: 17,
          won: 1,
          for: 10,
          drawn: 1,
          played: 7,
        },
        id: 29,
        position: 15,
        'total-points': 15,
      },
      {
        'all-matches': {
          lost: 9,
          against: 17,
          'goal-difference': -5,
          won: 4,
          for: 12,
          drawn: 2,
          played: 15,
        },
        zone: 'Play-offs (down)',
        name: 'West Ham United',
        'home-matches': {
          lost: 4,
          against: 10,
          won: 3,
          for: 9,
          drawn: 1,
          played: 8,
        },
        'away-matches': {
          lost: 5,
          against: 7,
          won: 1,
          for: 3,
          drawn: 1,
          played: 7,
        },
        id: 42,
        position: 16,
        'total-points': 14,
      },
      {
        'all-matches': {
          lost: 7,
          against: 17,
          'goal-difference': -6,
          won: 3,
          for: 11,
          drawn: 5,
          played: 15,
        },
        zone: 'Play-offs (down)',
        name: 'Everton',
        'home-matches': {
          lost: 3,
          against: 6,
          won: 2,
          for: 6,
          drawn: 2,
          played: 7,
        },
        'away-matches': {
          lost: 4,
          against: 11,
          won: 1,
          for: 5,
          drawn: 3,
          played: 8,
        },
        id: 9,
        position: 17,
        'total-points': 14,
      },
      {
        'all-matches': {
          lost: 8,
          against: 30,
          'goal-difference': -19,
          won: 3,
          for: 11,
          drawn: 4,
          played: 15,
        },
        zone: 'Relegation',
        name: 'Nottingham Forest',
        'home-matches': {
          lost: 3,
          against: 11,
          won: 3,
          for: 10,
          drawn: 2,
          played: 8,
        },
        'away-matches': {
          lost: 5,
          against: 19,
          won: 0,
          for: 1,
          drawn: 2,
          played: 7,
        },
        id: 32,
        position: 18,
        'total-points': 13,
      },
      {
        'all-matches': {
          lost: 9,
          against: 27,
          'goal-difference': -14,
          won: 3,
          for: 13,
          drawn: 3,
          played: 15,
        },
        zone: 'Relegation',
        name: 'Southampton',
        'home-matches': {
          lost: 3,
          against: 12,
          won: 1,
          for: 8,
          drawn: 3,
          played: 7,
        },
        'away-matches': {
          lost: 6,
          against: 15,
          won: 2,
          for: 5,
          drawn: 0,
          played: 8,
        },
        id: 18,
        position: 19,
        'total-points': 12,
      },
      {
        'all-matches': {
          lost: 9,
          against: 24,
          'goal-difference': -16,
          won: 2,
          for: 8,
          drawn: 4,
          played: 15,
        },
        zone: 'Relegation',
        name: 'Wolverhampton Wanderers',
        'home-matches': {
          lost: 4,
          against: 13,
          won: 2,
          for: 5,
          drawn: 2,
          played: 8,
        },
        'away-matches': {
          lost: 5,
          against: 11,
          won: 0,
          for: 3,
          drawn: 2,
          played: 7,
        },
        id: 44,
        position: 20,
        'total-points': 10,
      },
    ],
    description: 'League Table',
    competition: {
      name: 'Premier League',
      id: 1,
    },
  },
};

export const northernPremierMidlandsData: LeagueTableRes = {
  'league-table': {
    teams: [
      {
        'all-matches': {
          lost: 4,
          against: 21,
          'goal-difference': 26,
          won: 15,
          for: 47,
          drawn: 0,
          played: 19,
        },
        zone: 'Promotion',
        name: 'Halesowen Town',
        'home-matches': {
          lost: 0,
          against: 5,
          won: 9,
          for: 24,
          drawn: 0,
          played: 9,
        },
        'away-matches': {
          lost: 4,
          against: 16,
          won: 6,
          for: 23,
          drawn: 0,
          played: 10,
        },
        id: 169,
        position: 1,
        'total-points': 45,
      },
      {
        'all-matches': {
          lost: 3,
          against: 19,
          'goal-difference': 22,
          won: 14,
          for: 41,
          drawn: 2,
          played: 19,
        },
        zone: 'Play-offs (up)',
        name: 'Stamford',
        'home-matches': {
          lost: 1,
          against: 9,
          won: 7,
          for: 18,
          drawn: 1,
          played: 9,
        },
        'away-matches': {
          lost: 2,
          against: 10,
          won: 7,
          for: 23,
          drawn: 1,
          played: 10,
        },
        id: 178,
        position: 2,
        'total-points': 44,
      },
      {
        'all-matches': {
          lost: 0,
          against: 12,
          'goal-difference': 26,
          won: 12,
          for: 38,
          drawn: 6,
          played: 18,
        },
        zone: 'Play-offs (up)',
        name: 'Spalding United',
        'home-matches': {
          lost: 0,
          against: 10,
          won: 6,
          for: 22,
          drawn: 3,
          played: 9,
        },
        'away-matches': {
          lost: 0,
          against: 2,
          won: 6,
          for: 16,
          drawn: 3,
          played: 9,
        },
        id: 324,
        position: 3,
        'total-points': 42,
      },
      {
        'all-matches': {
          lost: 5,
          against: 26,
          'goal-difference': 19,
          won: 13,
          for: 45,
          drawn: 2,
          played: 20,
        },
        zone: 'Play-offs (up)',
        name: 'Sporting Khalsa',
        'home-matches': {
          lost: 4,
          against: 14,
          won: 6,
          for: 22,
          drawn: 0,
          played: 10,
        },
        'away-matches': {
          lost: 1,
          against: 12,
          won: 7,
          for: 23,
          drawn: 2,
          played: 10,
        },
        id: 1554,
        position: 4,
        'total-points': 41,
      },
      {
        'all-matches': {
          lost: 5,
          against: 21,
          'goal-difference': 12,
          won: 11,
          for: 33,
          drawn: 3,
          played: 19,
        },
        zone: 'Play-offs (up)',
        name: 'Boldmere St Michaels',
        'home-matches': {
          lost: 1,
          against: 10,
          won: 6,
          for: 20,
          drawn: 2,
          played: 9,
        },
        'away-matches': {
          lost: 4,
          against: 11,
          won: 5,
          for: 13,
          drawn: 1,
          played: 10,
        },
        id: 830,
        position: 5,
        'total-points': 36,
      },
      {
        'all-matches': {
          lost: 6,
          against: 23,
          'goal-difference': 13,
          won: 9,
          for: 36,
          drawn: 4,
          played: 19,
        },
        name: 'Coleshill Town',
        'home-matches': {
          lost: 2,
          against: 10,
          won: 6,
          for: 20,
          drawn: 1,
          played: 9,
        },
        'away-matches': {
          lost: 4,
          against: 13,
          won: 3,
          for: 16,
          drawn: 3,
          played: 10,
        },
        id: 700,
        position: 6,
        'total-points': 31,
      },
      {
        'all-matches': {
          lost: 4,
          against: 26,
          'goal-difference': 8,
          won: 8,
          for: 34,
          drawn: 7,
          played: 19,
        },
        name: 'Corby Town',
        'home-matches': {
          lost: 2,
          against: 13,
          won: 4,
          for: 15,
          drawn: 4,
          played: 10,
        },
        'away-matches': {
          lost: 2,
          against: 13,
          won: 4,
          for: 19,
          drawn: 3,
          played: 9,
        },
        id: 211,
        position: 7,
        'total-points': 31,
      },
      {
        'all-matches': {
          lost: 6,
          against: 19,
          'goal-difference': 7,
          won: 9,
          for: 26,
          drawn: 3,
          played: 18,
        },
        name: 'Loughborough Dynamo',
        'home-matches': {
          lost: 2,
          against: 8,
          won: 5,
          for: 11,
          drawn: 2,
          played: 9,
        },
        'away-matches': {
          lost: 4,
          against: 11,
          won: 4,
          for: 15,
          drawn: 1,
          played: 9,
        },
        id: 749,
        position: 8,
        'total-points': 30,
      },
      {
        'all-matches': {
          lost: 6,
          against: 31,
          'goal-difference': 10,
          won: 8,
          for: 41,
          drawn: 5,
          played: 19,
        },
        name: 'Harborough Town',
        'home-matches': {
          lost: 3,
          against: 15,
          won: 4,
          for: 23,
          drawn: 3,
          played: 10,
        },
        'away-matches': {
          lost: 3,
          against: 16,
          won: 4,
          for: 18,
          drawn: 2,
          played: 9,
        },
        id: 1415,
        position: 9,
        'total-points': 29,
      },
      {
        'all-matches': {
          lost: 8,
          against: 23,
          'goal-difference': 10,
          won: 8,
          for: 33,
          drawn: 3,
          played: 19,
        },
        name: 'Shepshed Dynamo',
        'home-matches': {
          lost: 4,
          against: 13,
          won: 3,
          for: 15,
          drawn: 2,
          played: 9,
        },
        'away-matches': {
          lost: 4,
          against: 10,
          won: 5,
          for: 18,
          drawn: 1,
          played: 10,
        },
        id: 323,
        position: 10,
        'total-points': 27,
      },
      {
        'all-matches': {
          lost: 6,
          against: 24,
          'goal-difference': -3,
          won: 6,
          for: 21,
          drawn: 7,
          played: 19,
        },
        name: 'Bedworth United',
        'home-matches': {
          lost: 3,
          against: 11,
          won: 4,
          for: 12,
          drawn: 3,
          played: 10,
        },
        'away-matches': {
          lost: 3,
          against: 13,
          won: 2,
          for: 9,
          drawn: 4,
          played: 9,
        },
        id: 204,
        position: 11,
        'total-points': 25,
      },
      {
        'all-matches': {
          lost: 11,
          against: 33,
          'goal-difference': -3,
          won: 7,
          for: 30,
          drawn: 0,
          played: 18,
        },
        name: 'Sutton Coldfield Town',
        'home-matches': {
          lost: 6,
          against: 19,
          won: 4,
          for: 20,
          drawn: 0,
          played: 10,
        },
        'away-matches': {
          lost: 5,
          against: 14,
          won: 3,
          for: 10,
          drawn: 0,
          played: 8,
        },
        id: 220,
        position: 12,
        'total-points': 21,
      },
      {
        'all-matches': {
          lost: 10,
          against: 21,
          'goal-difference': -3,
          won: 6,
          for: 18,
          drawn: 2,
          played: 18,
        },
        name: 'Hinckley LRFC',
        'home-matches': {
          lost: 3,
          against: 7,
          won: 5,
          for: 15,
          drawn: 1,
          played: 9,
        },
        'away-matches': {
          lost: 7,
          against: 14,
          won: 1,
          for: 3,
          drawn: 1,
          played: 9,
        },
        id: 2588,
        position: 13,
        'total-points': 20,
      },
      {
        'all-matches': {
          lost: 8,
          against: 25,
          'goal-difference': -10,
          won: 5,
          for: 15,
          drawn: 5,
          played: 18,
        },
        name: 'Cambridge City',
        'home-matches': {
          lost: 3,
          against: 11,
          won: 2,
          for: 6,
          drawn: 3,
          played: 8,
        },
        'away-matches': {
          lost: 5,
          against: 14,
          won: 3,
          for: 9,
          drawn: 2,
          played: 10,
        },
        id: 140,
        position: 14,
        'total-points': 20,
      },
      {
        'all-matches': {
          lost: 8,
          against: 17,
          'goal-difference': -3,
          won: 5,
          for: 14,
          drawn: 4,
          played: 17,
        },
        name: 'Chasetown',
        'home-matches': {
          lost: 4,
          against: 8,
          won: 3,
          for: 7,
          drawn: 2,
          played: 9,
        },
        'away-matches': {
          lost: 4,
          against: 9,
          won: 2,
          for: 7,
          drawn: 2,
          played: 8,
        },
        id: 384,
        position: 15,
        'total-points': 19,
      },
      {
        'all-matches': {
          lost: 10,
          against: 39,
          'goal-difference': -19,
          won: 5,
          for: 20,
          drawn: 3,
          played: 18,
        },
        name: 'Dereham Town',
        'home-matches': {
          lost: 4,
          against: 16,
          won: 4,
          for: 14,
          drawn: 2,
          played: 10,
        },
        'away-matches': {
          lost: 6,
          against: 23,
          won: 1,
          for: 6,
          drawn: 1,
          played: 8,
        },
        id: 708,
        position: 16,
        'total-points': 18,
      },
      {
        'all-matches': {
          lost: 12,
          against: 39,
          'goal-difference': -20,
          won: 5,
          for: 19,
          drawn: 2,
          played: 19,
        },
        zone: 'Play-offs (down)',
        name: 'Daventry Town',
        'home-matches': {
          lost: 5,
          against: 16,
          won: 4,
          for: 12,
          drawn: 0,
          played: 9,
        },
        'away-matches': {
          lost: 7,
          against: 23,
          won: 1,
          for: 7,
          drawn: 2,
          played: 10,
        },
        id: 707,
        position: 17,
        'total-points': 17,
      },
      {
        'all-matches': {
          lost: 11,
          against: 34,
          'goal-difference': -17,
          won: 4,
          for: 17,
          drawn: 4,
          played: 19,
        },
        zone: 'Play-offs (down)',
        name: 'Gresley Rovers',
        'home-matches': {
          lost: 5,
          against: 16,
          won: 3,
          for: 11,
          drawn: 2,
          played: 10,
        },
        'away-matches': {
          lost: 6,
          against: 18,
          won: 1,
          for: 6,
          drawn: 2,
          played: 9,
        },
        id: 314,
        position: 18,
        'total-points': 16,
      },
      {
        'all-matches': {
          lost: 12,
          against: 43,
          'goal-difference': -24,
          won: 3,
          for: 19,
          drawn: 3,
          played: 18,
        },
        zone: 'Relegation',
        name: 'St Neots Town',
        'home-matches': {
          lost: 6,
          against: 18,
          won: 2,
          for: 11,
          drawn: 1,
          played: 9,
        },
        'away-matches': {
          lost: 6,
          against: 25,
          won: 1,
          for: 8,
          drawn: 2,
          played: 9,
        },
        id: 895,
        position: 19,
        'total-points': 12,
      },
      {
        'all-matches': {
          lost: 18,
          against: 65,
          'goal-difference': -51,
          won: 0,
          for: 14,
          drawn: 1,
          played: 19,
        },
        zone: 'Relegation',
        name: 'Yaxley',
        'home-matches': {
          lost: 8,
          against: 29,
          won: 0,
          for: 5,
          drawn: 1,
          played: 9,
        },
        'away-matches': {
          lost: 10,
          against: 36,
          won: 0,
          for: 9,
          drawn: 0,
          played: 10,
        },
        id: 474,
        position: 20,
        'total-points': 1,
      },
    ],
    description: 'League Table',
    competition: {
      name: 'Northern Premier League - Midlands Division',
      id: 114,
    },
  },
};
